engines:
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR1,PSR2"
      ignore_warnings: true
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "phpmd.xml"
  markdownlint:
    enabled: true
ratings:
  paths:
  - "**.php"
exclude_paths:
  - examples/**/*
  - tests/**/*
  - "**/vendor/**/*"
